--
-- PostgreSQL database dump
--


-- Dumped from database version 16.15 (Debian 16.15-1.pgdg13+2)
-- Dumped by pg_dump version 16.15 (Debian 16.15-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: casting; Type: TABLE; Schema: public; Owner: yoda
--

CREATE TABLE public.casting (
    film_id integer NOT NULL,
    personne_id integer NOT NULL,
    role character varying(12) NOT NULL,
    CONSTRAINT casting_role_check CHECK (((role)::text = ANY ((ARRAY['acteur'::character varying, 'realisateur'::character varying])::text[])))
);


ALTER TABLE public.casting OWNER TO yoda;

--
-- Name: films; Type: TABLE; Schema: public; Owner: yoda
--

CREATE TABLE public.films (
    id integer NOT NULL,
    titre character varying(120) NOT NULL,
    annee integer NOT NULL,
    genre character varying(30) NOT NULL,
    saga_id integer,
    film_precedent_id integer,
    details jsonb NOT NULL,
    CONSTRAINT films_annee_check CHECK (((annee >= 1888) AND (annee <= 2100)))
);


ALTER TABLE public.films OWNER TO yoda;

--
-- Name: films_id_seq; Type: SEQUENCE; Schema: public; Owner: yoda
--

ALTER TABLE public.films ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.films_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: journal; Type: TABLE; Schema: public; Owner: yoda
--

CREATE TABLE public.journal (
    id integer NOT NULL,
    utilisateur_id integer NOT NULL,
    film_id integer NOT NULL,
    date_visionnage date NOT NULL
);


ALTER TABLE public.journal OWNER TO yoda;

--
-- Name: journal_id_seq; Type: SEQUENCE; Schema: public; Owner: yoda
--

ALTER TABLE public.journal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.journal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: liste; Type: TABLE; Schema: public; Owner: yoda
--

CREATE TABLE public.liste (
    id integer NOT NULL,
    membre character varying(100) NOT NULL,
    titre character varying(100) NOT NULL,
    visibility character varying(12) DEFAULT 'priv‚'::character varying,
    create_at date DEFAULT now(),
    CONSTRAINT liste_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['public'::character varying, 'priv‚'::character varying])::text[])))
);


ALTER TABLE public.liste OWNER TO yoda;

--
-- Name: liste_film; Type: TABLE; Schema: public; Owner: yoda
--

CREATE TABLE public.liste_film (
    id integer NOT NULL,
    liste_id integer NOT NULL,
    film character varying(100) NOT NULL,
    "position" integer NOT NULL,
    CONSTRAINT positif CHECK (("position" > 0))
);


ALTER TABLE public.liste_film OWNER TO yoda;

--
-- Name: liste_film_id_seq; Type: SEQUENCE; Schema: public; Owner: yoda
--

ALTER TABLE public.liste_film ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.liste_film_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: liste_id_seq; Type: SEQUENCE; Schema: public; Owner: yoda
--

ALTER TABLE public.liste ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.liste_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notes; Type: TABLE; Schema: public; Owner: yoda
--

CREATE TABLE public.notes (
    utilisateur_id integer NOT NULL,
    film_id integer NOT NULL,
    note numeric(2,1) NOT NULL,
    note_le date NOT NULL,
    CONSTRAINT notes_note_check CHECK (((note >= 0.5) AND (note <= (5)::numeric)))
);


ALTER TABLE public.notes OWNER TO yoda;

--
-- Name: mv_stats_films; Type: MATERIALIZED VIEW; Schema: public; Owner: yoda
--

CREATE MATERIALIZED VIEW public.mv_stats_films AS
 SELECT film_id,
    count(*) AS nb_notes,
    round(avg(note), 2) AS moyenne
   FROM public.notes
  GROUP BY film_id
  WITH NO DATA;


ALTER MATERIALIZED VIEW public.mv_stats_films OWNER TO yoda;

--
-- Name: personnes; Type: TABLE; Schema: public; Owner: yoda
--

CREATE TABLE public.personnes (
    id integer NOT NULL,
    nom character varying(80) NOT NULL
);


ALTER TABLE public.personnes OWNER TO yoda;

--
-- Name: personnes_id_seq; Type: SEQUENCE; Schema: public; Owner: yoda
--

ALTER TABLE public.personnes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.personnes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sagas; Type: TABLE; Schema: public; Owner: yoda
--

CREATE TABLE public.sagas (
    id integer NOT NULL,
    nom character varying(60) NOT NULL
);


ALTER TABLE public.sagas OWNER TO yoda;

--
-- Name: sagas_id_seq; Type: SEQUENCE; Schema: public; Owner: yoda
--

ALTER TABLE public.sagas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sagas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: utilisateurs; Type: TABLE; Schema: public; Owner: yoda
--

CREATE TABLE public.utilisateurs (
    id integer NOT NULL,
    pseudo character varying(30) NOT NULL,
    ville character varying(50),
    inscrit_le date NOT NULL
);


ALTER TABLE public.utilisateurs OWNER TO yoda;

--
-- Name: utilisateurs_id_seq; Type: SEQUENCE; Schema: public; Owner: yoda
--

ALTER TABLE public.utilisateurs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.utilisateurs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: v_fiche_film; Type: VIEW; Schema: public; Owner: yoda
--

CREATE VIEW public.v_fiche_film AS
 SELECT f.id,
    f.titre,
    f.annee,
    f.genre,
    r.realisateurs,
    ((f.details ->> 'duree'::text))::integer AS duree_min,
    s.nb_notes,
    s.moyenne
   FROM ((public.films f
     LEFT JOIN LATERAL ( SELECT string_agg((p.nom)::text, ', '::text ORDER BY (p.nom)::text) AS realisateurs
           FROM (public.casting c
             JOIN public.personnes p ON ((p.id = c.personne_id)))
          WHERE ((c.film_id = f.id) AND ((c.role)::text = 'realisateur'::text))) r ON (true))
     LEFT JOIN LATERAL ( SELECT count(*) AS nb_notes,
            round(avg(n.note), 2) AS moyenne
           FROM public.notes n
          WHERE (n.film_id = f.id)) s ON (true));


ALTER VIEW public.v_fiche_film OWNER TO yoda;

--
-- Name: v_films_sf; Type: VIEW; Schema: public; Owner: yoda
--

CREATE VIEW public.v_films_sf AS
 SELECT id,
    titre,
    annee,
    genre
   FROM public.films
  WHERE ((genre)::text = 'Science-fiction'::text)
  WITH CASCADED CHECK OPTION;


ALTER VIEW public.v_films_sf OWNER TO yoda;

--
-- Data for Name: casting; Type: TABLE DATA; Schema: public; Owner: yoda
--

COPY public.casting (film_id, personne_id, role) FROM stdin;
1	68	acteur
1	38	acteur
1	5	acteur
1	21	acteur
1	14	acteur
1	61	realisateur
2	63	acteur
2	66	acteur
2	38	acteur
2	39	acteur
2	11	realisateur
3	67	acteur
3	28	acteur
3	13	acteur
3	38	acteur
3	60	realisateur
4	30	acteur
4	50	acteur
4	33	acteur
4	38	acteur
4	48	realisateur
5	27	acteur
5	30	acteur
5	50	acteur
5	33	acteur
5	56	acteur
5	7	realisateur
6	30	acteur
6	50	acteur
6	33	acteur
6	7	realisateur
7	68	acteur
7	59	acteur
7	21	acteur
7	58	realisateur
8	68	acteur
8	25	acteur
8	58	realisateur
9	68	acteur
9	47	acteur
9	70	acteur
9	72	acteur
9	65	realisateur
10	41	acteur
10	68	acteur
10	65	realisateur
11	41	acteur
11	37	acteur
11	29	realisateur
12	41	acteur
12	35	acteur
12	16	acteur
12	69	acteur
12	44	acteur
12	49	acteur
12	10	realisateur
13	41	acteur
13	47	acteur
13	28	acteur
13	45	realisateur
14	41	acteur
14	6	acteur
14	43	acteur
14	57	realisateur
15	41	acteur
15	34	acteur
15	43	acteur
15	31	acteur
15	45	realisateur
16	6	acteur
16	15	acteur
16	24	acteur
16	12	realisateur
17	22	acteur
17	6	acteur
17	47	acteur
17	36	acteur
17	64	realisateur
18	6	acteur
18	53	acteur
18	12	realisateur
19	8	acteur
19	49	acteur
19	42	acteur
19	53	acteur
19	20	acteur
19	10	realisateur
20	8	acteur
20	23	acteur
20	49	acteur
20	53	acteur
20	20	acteur
20	10	realisateur
21	8	acteur
21	69	acteur
21	1	acteur
21	35	acteur
21	44	acteur
21	49	acteur
21	20	acteur
21	53	acteur
21	10	realisateur
22	66	acteur
22	53	acteur
22	18	realisateur
23	17	acteur
23	56	acteur
23	55	realisateur
23	2	realisateur
24	44	acteur
24	19	acteur
24	54	realisateur
25	31	acteur
25	4	acteur
25	52	realisateur
26	3	acteur
26	46	acteur
26	32	realisateur
27	71	acteur
27	26	acteur
27	62	acteur
27	46	realisateur
28	51	acteur
28	9	acteur
28	40	acteur
28	58	realisateur
29	51	acteur
29	9	acteur
29	40	acteur
29	58	realisateur
30	51	acteur
30	9	acteur
30	40	acteur
30	58	realisateur
\.


--
-- Data for Name: films; Type: TABLE DATA; Schema: public; Owner: yoda
--

COPY public.films (id, titre, annee, genre, saga_id, film_precedent_id, details) FROM stdin;
1	Apollo 13	1995	Drame	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["espace", "histoire vraie"], "duree": 140, "langue": "anglais"}
2	Mystic River	2003	Thriller	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["enquÃªte", "drame familial"], "duree": 138, "langue": "anglais"}
3	Des hommes d'honneur	1992	Drame	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["procÃ¨s", "armÃ©e"], "duree": 138, "langue": "anglais"}
4	X-Men : Le Commencement	2011	Science-fiction	3	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["super-hÃ©ros", "mutants"], "duree": 132, "langue": "anglais"}
7	Forrest Gump	1994	Drame	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["destin", "histoire amÃ©ricaine"], "duree": 142, "langue": "anglais", "oscar_meilleur_film": true}
8	Seul au monde	2000	Aventure	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["survie", "Ã®le"], "duree": 143, "langue": "anglais"}
9	Il faut sauver le soldat Ryan	1998	Guerre	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["seconde guerre mondiale"], "duree": 169, "langue": "anglais"}
10	ArrÃªte-moi si tu peux	2002	Policier	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["histoire vraie", "arnaque"], "duree": 141, "langue": "anglais"}
11	Titanic	1997	Romance	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["romance", "naufrage"], "duree": 194, "langue": "anglais", "oscar_meilleur_film": true}
12	Inception	2010	Science-fiction	\N	\N	{"pays": ["Ã‰tats-Unis", "Royaume-Uni"], "tags": ["rÃªves", "braquage"], "duree": 148, "langue": "anglais"}
13	Les InfiltrÃ©s	2006	Policier	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["mafia", "remake"], "duree": 151, "langue": "anglais", "oscar_meilleur_film": true}
14	Once Upon a Timeâ€¦ in Hollywood	2019	ComÃ©die	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["Hollywood", "annÃ©es 60"], "duree": 161, "langue": "anglais"}
15	Le Loup de Wall Street	2013	ComÃ©die	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["histoire vraie", "finance"], "duree": 180, "langue": "anglais"}
16	Fight Club	1999	Thriller	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["culte", "twist"], "duree": 139, "langue": "anglais"}
17	Ocean's Eleven	2001	Policier	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["braquage", "Las Vegas"], "duree": 116, "langue": "anglais"}
18	Seven	1995	Thriller	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["enquÃªte", "tueur en sÃ©rie", "twist"], "duree": 127, "langue": "anglais"}
19	Batman Begins	2005	Action	2	\N	{"pays": ["Ã‰tats-Unis", "Royaume-Uni"], "tags": ["super-hÃ©ros", "Gotham"], "duree": 140, "langue": "anglais"}
22	Les Ã‰vadÃ©s	1994	Drame	\N	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["prison", "amitiÃ©", "culte"], "duree": 142, "langue": "anglais"}
23	Intouchables	2011	ComÃ©die	\N	\N	{"pays": ["France"], "tags": ["histoire vraie", "amitiÃ©"], "duree": 112, "langue": "franÃ§ais"}
24	La MÃ´me	2007	Drame	\N	\N	{"pays": ["France"], "tags": ["biopic", "musique"], "duree": 140, "langue": "franÃ§ais"}
25	The Artist	2011	ComÃ©die	\N	\N	{"pays": ["France"], "tags": ["cinÃ©ma muet", "Hollywood"], "duree": 100, "langue": "muet", "oscar_meilleur_film": true}
26	Le Fabuleux Destin d'AmÃ©lie Poulain	2001	ComÃ©die	\N	\N	{"pays": ["France"], "tags": ["Paris", "culte"], "duree": 122, "langue": "franÃ§ais"}
27	La Haine	1995	Drame	\N	\N	{"pays": ["France"], "tags": ["banlieue", "noir et blanc", "culte"], "duree": 98, "langue": "franÃ§ais"}
28	Retour vers le futur	1985	Science-fiction	1	\N	{"pays": ["Ã‰tats-Unis"], "tags": ["voyage dans le temps", "culte"], "duree": 116, "langue": "anglais"}
5	X-Men : Days of Future Past	2014	Science-fiction	3	4	{"pays": ["Ã‰tats-Unis"], "tags": ["super-hÃ©ros", "mutants", "voyage dans le temps"], "duree": 132, "langue": "anglais"}
6	X-Men : Apocalypse	2016	Science-fiction	3	5	{"pays": ["Ã‰tats-Unis"], "tags": ["super-hÃ©ros", "mutants"], "duree": 144, "langue": "anglais"}
20	The Dark Knight	2008	Action	2	19	{"pays": ["Ã‰tats-Unis", "Royaume-Uni"], "tags": ["super-hÃ©ros", "Gotham", "culte"], "duree": 152, "langue": "anglais"}
21	The Dark Knight Rises	2012	Action	2	20	{"pays": ["Ã‰tats-Unis", "Royaume-Uni"], "tags": ["super-hÃ©ros", "Gotham"], "duree": 164, "langue": "anglais"}
29	Retour vers le futur II	1989	Science-fiction	1	28	{"pays": ["Ã‰tats-Unis"], "tags": ["voyage dans le temps"], "duree": 108, "langue": "anglais"}
30	Retour vers le futur III	1990	Science-fiction	1	29	{"pays": ["Ã‰tats-Unis"], "tags": ["voyage dans le temps", "western"], "duree": 118, "langue": "anglais"}
\.


--
-- Data for Name: journal; Type: TABLE DATA; Schema: public; Owner: yoda
--

COPY public.journal (id, utilisateur_id, film_id, date_visionnage) FROM stdin;
1	1	1	2026-05-12
2	2	1	2026-05-16
3	4	1	2026-05-23
4	5	1	2026-09-05
5	8	1	2026-06-14
6	1	2	2026-07-03
7	4	2	2026-04-13
8	6	2	2026-01-13
9	7	2	2026-09-08
10	2	3	2026-07-24
11	3	3	2026-03-25
12	4	3	2026-08-30
13	5	3	2026-03-24
14	6	3	2026-01-10
15	8	3	2026-01-08
16	1	4	2026-09-16
17	2	4	2026-06-12
18	7	4	2026-02-16
19	1	5	2026-07-18
20	3	5	2026-01-08
21	5	5	2026-02-12
22	7	5	2026-09-07
23	8	5	2026-07-10
24	1	6	2026-04-27
25	2	6	2026-02-08
26	4	6	2026-04-03
27	5	6	2026-03-29
28	6	6	2026-05-24
29	7	6	2026-03-08
30	1	7	2026-07-05
31	2	7	2026-02-10
32	4	7	2026-06-11
33	5	7	2026-03-21
34	6	7	2026-07-13
35	1	8	2026-01-06
36	2	8	2026-08-20
37	3	8	2026-05-05
38	4	8	2026-03-26
39	5	8	2026-05-30
40	6	8	2026-06-02
41	7	8	2026-03-26
42	1	9	2026-07-09
43	4	9	2026-05-03
44	5	9	2026-04-15
45	6	9	2026-09-09
46	7	9	2026-08-08
47	8	9	2026-08-12
48	2	10	2026-09-03
49	3	10	2026-01-15
50	4	10	2026-07-14
51	5	10	2026-06-03
52	6	10	2026-01-08
53	1	11	2026-04-03
54	3	11	2026-03-22
55	4	11	2026-02-08
56	5	11	2026-05-29
57	7	11	2026-08-23
58	1	12	2026-08-18
59	3	12	2026-05-13
60	5	12	2026-02-17
61	6	12	2026-03-13
62	7	12	2026-06-26
63	1	13	2026-04-20
64	3	13	2026-09-14
65	4	13	2026-06-22
66	5	13	2026-09-05
67	6	13	2026-09-02
68	7	13	2026-03-26
69	8	13	2026-04-15
70	1	14	2026-04-24
71	2	14	2026-01-21
72	3	14	2026-04-20
73	4	14	2026-08-20
74	6	14	2026-07-14
75	7	14	2026-06-05
76	2	15	2026-08-23
77	3	15	2026-08-25
78	4	15	2026-08-17
79	5	15	2026-05-31
80	7	15	2026-09-07
81	3	16	2026-08-15
82	6	16	2026-06-12
83	7	16	2026-04-22
84	8	16	2026-02-13
85	1	17	2026-04-09
86	2	17	2026-01-08
87	3	17	2026-01-17
88	4	17	2026-07-10
89	5	17	2026-08-30
90	6	17	2026-02-04
91	8	17	2026-07-22
92	1	18	2026-03-02
93	2	18	2026-07-13
94	3	18	2026-03-30
95	4	18	2026-08-25
96	5	18	2026-08-30
97	6	18	2026-02-23
98	2	19	2026-03-23
99	3	19	2026-03-25
100	4	19	2026-04-13
101	6	19	2026-01-31
102	7	19	2026-05-19
103	1	20	2026-01-19
104	4	20	2026-02-24
105	5	20	2026-05-10
106	6	20	2026-08-13
107	7	20	2026-01-30
108	6	21	2026-07-10
109	7	21	2026-06-11
110	8	21	2026-07-06
111	1	22	2026-05-17
112	2	22	2026-02-12
113	5	22	2026-07-12
114	6	22	2026-06-27
115	1	23	2026-04-24
116	2	23	2026-03-26
117	3	23	2026-06-05
118	7	23	2026-04-22
119	8	23	2026-05-09
120	1	24	2026-04-03
121	2	24	2026-03-08
122	4	24	2026-03-15
123	5	24	2026-07-15
124	7	24	2026-08-17
125	8	24	2026-06-06
126	1	25	2026-06-19
127	3	25	2026-05-18
128	5	25	2026-04-01
129	6	25	2026-04-12
130	7	25	2026-04-13
131	8	25	2026-08-19
132	3	26	2026-04-30
133	4	26	2026-07-28
134	5	26	2026-01-19
135	6	26	2026-07-17
136	7	26	2026-09-12
137	4	27	2026-08-21
138	5	27	2026-06-21
139	6	27	2026-06-15
140	8	27	2026-09-16
141	1	28	2026-03-06
142	2	28	2026-01-21
143	3	28	2026-09-05
144	4	28	2026-09-15
145	5	28	2026-09-10
146	7	28	2026-05-01
147	8	28	2026-04-30
148	1	29	2026-06-29
149	3	29	2026-07-29
150	4	29	2026-06-01
151	5	29	2026-06-07
152	7	29	2026-03-23
153	2	30	2026-01-15
154	3	30	2026-02-09
155	4	30	2026-01-19
156	5	30	2026-02-01
157	6	30	2026-06-18
158	7	30	2026-05-23
159	8	30	2026-06-30
160	2	1	2026-06-16
161	1	2	2026-08-04
162	6	2	2026-02-14
163	7	4	2026-03-22
164	3	5	2026-02-12
165	2	7	2026-03-19
166	4	7	2026-07-18
167	6	7	2026-08-19
168	1	9	2026-08-17
169	4	9	2026-06-11
170	8	9	2026-09-20
171	3	10	2026-02-24
172	5	10	2026-07-13
173	6	10	2026-02-17
174	5	12	2026-03-31
175	6	12	2026-04-24
176	7	12	2026-08-07
177	4	13	2026-08-04
178	1	14	2026-06-07
179	5	15	2026-07-15
180	6	16	2026-07-28
181	3	17	2026-03-05
182	1	18	2026-04-19
183	2	18	2026-08-30
184	3	18	2026-05-17
185	6	19	2026-03-21
186	1	20	2026-02-18
187	4	20	2026-03-26
188	5	20	2026-06-09
189	6	20	2026-09-12
190	7	20	2026-03-01
191	7	21	2026-07-12
192	1	22	2026-06-18
193	2	22	2026-03-16
194	5	22	2026-08-13
195	1	23	2026-05-27
196	3	23	2026-07-08
197	2	24	2026-04-11
198	5	25	2026-05-06
199	4	26	2026-09-02
200	5	26	2026-02-24
201	5	27	2026-07-28
202	6	27	2026-07-22
203	1	28	2026-04-13
204	7	28	2026-06-08
205	3	30	2026-03-21
206	4	30	2026-02-28
207	6	30	2026-07-28
208	8	30	2026-08-09
\.


--
-- Data for Name: liste; Type: TABLE DATA; Schema: public; Owner: yoda
--

COPY public.liste (id, membre, titre, visibility, create_at) FROM stdin;
1	cinephile_92	Mon top Nolan	public	2026-09-27
\.


--
-- Data for Name: liste_film; Type: TABLE DATA; Schema: public; Owner: yoda
--

COPY public.liste_film (id, liste_id, film, "position") FROM stdin;
1	1	The Dark Knight	1
2	1	Inception	2
3	1	Batman Begins	3
\.


--
-- Data for Name: notes; Type: TABLE DATA; Schema: public; Owner: yoda
--

COPY public.notes (utilisateur_id, film_id, note, note_le) FROM stdin;
1	1	3.5	2026-05-12
2	1	4.5	2026-05-16
4	1	3.0	2026-05-23
5	1	4.0	2026-09-05
8	1	4.0	2026-06-14
1	2	4.5	2026-07-03
4	2	3.5	2026-04-13
6	2	4.5	2026-01-13
7	2	3.5	2026-09-08
2	3	3.5	2026-07-24
3	3	3.0	2026-03-25
4	3	4.0	2026-08-30
5	3	4.0	2026-03-24
6	3	3.0	2026-01-10
8	3	4.0	2026-01-08
1	4	3.5	2026-09-16
2	4	3.5	2026-06-12
7	4	4.5	2026-02-16
1	5	3.5	2026-07-18
3	5	4.5	2026-01-08
5	5	3.0	2026-02-12
7	5	4.5	2026-09-07
8	5	3.5	2026-07-10
1	6	2.5	2026-04-27
2	6	3.5	2026-02-08
4	6	3.0	2026-04-03
5	6	2.5	2026-03-29
6	6	3.0	2026-05-24
7	6	3.5	2026-03-08
1	7	4.0	2026-07-05
2	7	5.0	2026-02-10
4	7	4.5	2026-06-11
5	7	4.0	2026-03-21
6	7	4.5	2026-07-13
1	8	3.5	2026-01-06
2	8	3.0	2026-08-20
3	8	3.0	2026-05-05
4	8	3.0	2026-03-26
5	8	4.0	2026-05-30
6	8	3.5	2026-06-02
7	8	3.5	2026-03-26
1	9	4.5	2026-07-09
4	9	5.0	2026-05-03
5	9	4.0	2026-04-15
6	9	3.5	2026-09-09
7	9	3.5	2026-08-08
8	9	5.0	2026-08-12
2	10	5.0	2026-09-03
3	10	4.5	2026-01-15
4	10	4.0	2026-07-14
5	10	5.0	2026-06-03
6	10	4.5	2026-01-08
1	11	4.0	2026-04-03
3	11	4.0	2026-03-22
4	11	4.0	2026-02-08
5	11	4.0	2026-05-29
7	11	4.5	2026-08-23
1	12	5.0	2026-08-18
3	12	3.5	2026-05-13
5	12	5.0	2026-02-17
6	12	5.0	2026-03-13
7	12	4.5	2026-06-26
1	13	4.0	2026-04-20
3	13	4.0	2026-09-14
4	13	4.5	2026-06-22
5	13	4.0	2026-09-05
6	13	5.0	2026-09-02
7	13	4.0	2026-03-26
8	13	4.0	2026-04-15
1	14	4.5	2026-04-24
2	14	3.5	2026-01-21
3	14	3.0	2026-04-20
4	14	3.0	2026-08-20
6	14	3.0	2026-07-14
7	14	4.0	2026-06-05
2	15	4.0	2026-08-23
3	15	3.5	2026-08-25
4	15	5.0	2026-08-17
5	15	4.5	2026-05-31
7	15	4.0	2026-09-07
3	16	3.5	2026-08-15
6	16	4.5	2026-06-12
7	16	4.0	2026-04-22
8	16	4.0	2026-02-13
1	17	3.0	2026-04-09
2	17	3.0	2026-01-08
3	17	4.5	2026-01-17
4	17	4.0	2026-07-10
5	17	3.0	2026-08-30
6	17	4.0	2026-02-04
8	17	3.0	2026-07-22
1	18	5.0	2026-03-02
2	18	5.0	2026-07-13
3	18	5.0	2026-03-30
4	18	3.5	2026-08-25
5	18	4.5	2026-08-30
6	18	4.0	2026-02-23
2	19	4.0	2026-03-23
3	19	3.5	2026-03-25
4	19	4.0	2026-04-13
6	19	4.5	2026-01-31
7	19	4.0	2026-05-19
1	20	4.5	2026-01-19
4	20	4.5	2026-02-24
5	20	4.5	2026-05-10
6	20	4.5	2026-08-13
7	20	4.5	2026-01-30
6	21	3.5	2026-07-10
7	21	4.5	2026-06-11
8	21	4.0	2026-07-06
1	22	5.0	2026-05-17
2	22	4.5	2026-02-12
5	22	5.0	2026-07-12
6	22	4.0	2026-06-27
1	23	5.0	2026-04-24
2	23	3.5	2026-03-26
3	23	4.5	2026-06-05
7	23	4.0	2026-04-22
8	23	3.5	2026-05-09
1	24	4.0	2026-04-03
2	24	4.5	2026-03-08
4	24	3.0	2026-03-15
5	24	3.5	2026-07-15
7	24	3.0	2026-08-17
8	24	3.0	2026-06-06
1	25	3.5	2026-06-19
3	25	3.5	2026-05-18
5	25	4.5	2026-04-01
6	25	4.0	2026-04-12
7	25	4.0	2026-04-13
8	25	4.0	2026-08-19
3	26	3.5	2026-04-30
4	26	4.5	2026-07-28
5	26	4.5	2026-01-19
6	26	4.0	2026-07-17
7	26	4.0	2026-09-12
4	27	4.0	2026-08-21
5	27	5.0	2026-06-21
6	27	5.0	2026-06-15
8	27	5.0	2026-09-16
1	28	5.0	2026-03-06
2	28	4.0	2026-01-21
3	28	4.5	2026-09-05
4	28	5.0	2026-09-15
5	28	5.0	2026-09-10
7	28	5.0	2026-05-01
8	28	4.0	2026-04-30
1	29	4.0	2026-06-29
3	29	3.5	2026-07-29
4	29	4.0	2026-06-01
5	29	3.5	2026-06-07
7	29	4.0	2026-03-23
2	30	4.0	2026-01-15
3	30	4.5	2026-02-09
4	30	4.5	2026-01-19
5	30	3.5	2026-02-01
6	30	4.5	2026-06-18
7	30	4.0	2026-05-23
8	30	4.5	2026-06-30
8	12	2.0	2026-09-21
\.


--
-- Data for Name: personnes; Type: TABLE DATA; Schema: public; Owner: yoda
--

COPY public.personnes (id, nom) FROM stdin;
1	Anne Hathaway
2	Ã‰ric Toledano
3	Audrey Tautou
4	BÃ©rÃ©nice Bejo
5	Bill Paxton
6	Brad Pitt
7	Bryan Singer
8	Christian Bale
9	Christopher Lloyd
10	Christopher Nolan
11	Clint Eastwood
12	David Fincher
13	Demi Moore
14	Ed Harris
15	Edward Norton
16	Elliot Page
17	FranÃ§ois Cluzet
18	Frank Darabont
19	GÃ©rard Depardieu
20	Gary Oldman
21	Gary Sinise
22	George Clooney
23	Heath Ledger
24	Helena Bonham Carter
25	Helen Hunt
26	Hubert KoundÃ©
27	Hugh Jackman
28	Jack Nicholson
29	James Cameron
30	James McAvoy
31	Jean Dujardin
32	Jean-Pierre Jeunet
33	Jennifer Lawrence
34	Jonah Hill
35	Joseph Gordon-Levitt
36	Julia Roberts
37	Kate Winslet
38	Kevin Bacon
39	Laurence Fishburne
40	Lea Thompson
41	Leonardo DiCaprio
42	Liam Neeson
43	Margot Robbie
44	Marion Cotillard
45	Martin Scorsese
46	Mathieu Kassovitz
47	Matt Damon
48	Matthew Vaughn
49	Michael Caine
50	Michael Fassbender
51	Michael J. Fox
52	Michel Hazanavicius
53	Morgan Freeman
54	Olivier Dahan
55	Olivier Nakache
56	Omar Sy
57	Quentin Tarantino
58	Robert Zemeckis
59	Robin Wright
60	Rob Reiner
61	Ron Howard
62	SaÃ¯d Taghmaoui
63	Sean Penn
64	Steven Soderbergh
65	Steven Spielberg
66	Tim Robbins
67	Tom Cruise
68	Tom Hanks
69	Tom Hardy
70	Tom Sizemore
71	Vincent Cassel
72	Vin Diesel
\.


--
-- Data for Name: sagas; Type: TABLE DATA; Schema: public; Owner: yoda
--

COPY public.sagas (id, nom) FROM stdin;
1	Retour vers le futur
2	The Dark Knight
3	X-Men : la prÃ©logie
\.


--
-- Data for Name: utilisateurs; Type: TABLE DATA; Schema: public; Owner: yoda
--

COPY public.utilisateurs (id, pseudo, ville, inscrit_le) FROM stdin;
1	cinephile_92	Nanterre	2024-03-12
2	popcorn_queen	Lyon	2024-09-01
3	nolanfan	Paris	2025-01-05
4	maxou_cinÃ©	Marseille	2025-02-20
5	lea.reel	Lille	2025-04-02
6	darkroom	Nantes	2025-06-18
7	bobine	Bordeaux	2025-09-07
8	sofa_critic	Paris	2025-12-11
\.


--
-- Name: films_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoda
--

SELECT pg_catalog.setval('public.films_id_seq', 30, true);


--
-- Name: journal_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoda
--

SELECT pg_catalog.setval('public.journal_id_seq', 208, true);


--
-- Name: liste_film_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoda
--

SELECT pg_catalog.setval('public.liste_film_id_seq', 3, true);


--
-- Name: liste_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoda
--

SELECT pg_catalog.setval('public.liste_id_seq', 1, true);


--
-- Name: personnes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoda
--

SELECT pg_catalog.setval('public.personnes_id_seq', 72, true);


--
-- Name: sagas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoda
--

SELECT pg_catalog.setval('public.sagas_id_seq', 3, true);


--
-- Name: utilisateurs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: yoda
--

SELECT pg_catalog.setval('public.utilisateurs_id_seq', 8, true);


--
-- Name: casting casting_pkey; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.casting
    ADD CONSTRAINT casting_pkey PRIMARY KEY (film_id, personne_id, role);


--
-- Name: films films_pkey; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.films
    ADD CONSTRAINT films_pkey PRIMARY KEY (id);


--
-- Name: journal journal_pkey; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.journal
    ADD CONSTRAINT journal_pkey PRIMARY KEY (id);


--
-- Name: liste_film liste_film_pkey; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.liste_film
    ADD CONSTRAINT liste_film_pkey PRIMARY KEY (liste_id, film, id);


--
-- Name: liste liste_pkey; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.liste
    ADD CONSTRAINT liste_pkey PRIMARY KEY (id);


--
-- Name: notes notes_pkey; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_pkey PRIMARY KEY (utilisateur_id, film_id);


--
-- Name: personnes personnes_nom_key; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.personnes
    ADD CONSTRAINT personnes_nom_key UNIQUE (nom);


--
-- Name: personnes personnes_pkey; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.personnes
    ADD CONSTRAINT personnes_pkey PRIMARY KEY (id);


--
-- Name: sagas sagas_nom_key; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.sagas
    ADD CONSTRAINT sagas_nom_key UNIQUE (nom);


--
-- Name: sagas sagas_pkey; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.sagas
    ADD CONSTRAINT sagas_pkey PRIMARY KEY (id);


--
-- Name: liste_film unique_position; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.liste_film
    ADD CONSTRAINT unique_position UNIQUE (liste_id, "position");


--
-- Name: utilisateurs utilisateurs_pkey; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.utilisateurs
    ADD CONSTRAINT utilisateurs_pkey PRIMARY KEY (id);


--
-- Name: utilisateurs utilisateurs_pseudo_key; Type: CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.utilisateurs
    ADD CONSTRAINT utilisateurs_pseudo_key UNIQUE (pseudo);


--
-- Name: mv_stats_films_film_id_idx; Type: INDEX; Schema: public; Owner: yoda
--

CREATE UNIQUE INDEX mv_stats_films_film_id_idx ON public.mv_stats_films USING btree (film_id);


--
-- Name: casting casting_film_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.casting
    ADD CONSTRAINT casting_film_id_fkey FOREIGN KEY (film_id) REFERENCES public.films(id);


--
-- Name: casting casting_personne_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.casting
    ADD CONSTRAINT casting_personne_id_fkey FOREIGN KEY (personne_id) REFERENCES public.personnes(id);


--
-- Name: films films_film_precedent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.films
    ADD CONSTRAINT films_film_precedent_id_fkey FOREIGN KEY (film_precedent_id) REFERENCES public.films(id);


--
-- Name: films films_saga_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.films
    ADD CONSTRAINT films_saga_id_fkey FOREIGN KEY (saga_id) REFERENCES public.sagas(id);


--
-- Name: journal journal_film_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.journal
    ADD CONSTRAINT journal_film_id_fkey FOREIGN KEY (film_id) REFERENCES public.films(id);


--
-- Name: journal journal_utilisateur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.journal
    ADD CONSTRAINT journal_utilisateur_id_fkey FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateurs(id);


--
-- Name: notes notes_film_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_film_id_fkey FOREIGN KEY (film_id) REFERENCES public.films(id);


--
-- Name: notes notes_utilisateur_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: yoda
--

ALTER TABLE ONLY public.notes
    ADD CONSTRAINT notes_utilisateur_id_fkey FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateurs(id);


--
-- Name: mv_stats_films; Type: MATERIALIZED VIEW DATA; Schema: public; Owner: yoda
--

REFRESH MATERIALIZED VIEW public.mv_stats_films;


--
-- PostgreSQL database dump complete
--



-- =======================================================
-- Fonctions métiers FilmBox (issues de exo.sql)
-- =======================================================

SET search_path = public;

-- 10.1 Formatage de durée (ex: 148 -> '2 h 28')
CREATE OR REPLACE FUNCTION duree_texte(p_minutes INTEGER)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
AS $$
    SELECT (p_minutes / 60) || ' h ' || LPAD((p_minutes % 60)::TEXT, 2, '0');
$$;

-- 10.2 Calcul de la note pondérée bayésienne (m=5)
CREATE OR REPLACE FUNCTION note_ponderee(p_film_id INTEGER, p_m INTEGER DEFAULT 5)
RETURNS NUMERIC
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
    v_nb       INTEGER;
    v_moyenne  NUMERIC;
    v_globale  NUMERIC;
BEGIN
    SELECT COUNT(*), AVG(note) INTO v_nb, v_moyenne
    FROM notes WHERE film_id = p_film_id;

    IF v_nb = 0 THEN
        RETURN 0;
    END IF;

    SELECT AVG(note) INTO v_globale FROM notes;

    RETURN ROUND(  (v_nb::NUMERIC / (v_nb + p_m)) * v_moyenne
                 + (p_m::NUMERIC  / (v_nb + p_m)) * v_globale, 2);
END;
$$;

-- 10.3 Fonction de compatibilité cinéphile entre deux utilisateurs
CREATE OR REPLACE FUNCTION compatibilite(p_a TEXT, p_b TEXT)
RETURNS TABLE (titre VARCHAR, note_a NUMERIC, note_b NUMERIC, ecart NUMERIC)
LANGUAGE sql
STABLE
AS $$
    SELECT f.titre, na.note, nb.note, ABS(na.note - nb.note)
    FROM notes na
    JOIN utilisateurs ua ON ua.id = na.utilisateur_id AND ua.pseudo = p_a
    JOIN notes nb        ON nb.film_id = na.film_id
    JOIN utilisateurs ub ON ub.id = nb.utilisateur_id AND ub.pseudo = p_b
    JOIN films f         ON f.id = na.film_id
    ORDER BY ABS(na.note - nb.note) DESC, f.titre;
$$;

-- Réinitialisation de la version de collation pour compatibilité alpine/musl (évite tout warning de collation)
UPDATE pg_database SET datcollversion = NULL;

