import type {
  Film,
  FicheFilm,
  SagaEpisode,
  JournalEntry,
  Profil,
  Suggestion,
  RankingGenre,
  RankingDirector,
  PolarizingFilm,
  Liste,
  ListeDetail,
  BaconPath,
} from "@/types/api";

export const MOCK_FILMS: Film[] = [
  {
    id: "1",
    title: "Inception",
    originalTitle: "Inception",
    releaseYear: 2010,
    durationMinutes: 148,
    durationFormatted: "2h 28m",
    director: "Christopher Nolan",
    genres: ["Science-Fiction", "Action", "Thriller"],
    tags: ["Rêves", "Heist", "Mind-bending", "Culte"],
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    synopsis: "Dom Cobb est un voleur expérimenté, le meilleur dans l'art périlleux de l'extraction : s'emparer des secrets les plus précieux du subconscient d'une cible pendant son sommeil.",
    weightedRating: 4.8,
    ratingsCount: 14200,
    hasOscars: true,
    oscarsCount: 4,
    sagaId: "nolan-mind",
    details: {
      boxOffice: "$836M",
      budget: "$160M",
      country: "USA / UK",
      language: "Anglais",
      awards: "4 Oscars (Photographie, Effets Visuels, Son, Montage Sonore)",
    },
  },
  {
    id: "2",
    title: "Interstellar",
    originalTitle: "Interstellar",
    releaseYear: 2014,
    durationMinutes: 169,
    durationFormatted: "2h 49m",
    director: "Christopher Nolan",
    genres: ["Science-Fiction", "Drame", "Aventure"],
    tags: ["Espace", "Trous de ver", "Temps", "Amour paternel"],
    posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=1600&auto=format&fit=crop&q=80",
    synopsis: "Dans un futur proche où la Terre devient inhabitable, un groupe d'explorateurs franchit un trou de ver récemment découvert afin de trouver une nouvelle planète habitable pour l'humanité.",
    weightedRating: 4.9,
    ratingsCount: 18500,
    hasOscars: true,
    oscarsCount: 1,
    sagaId: "nolan-mind",
    details: {
      boxOffice: "$773M",
      budget: "$165M",
      country: "USA / UK",
      language: "Anglais",
      awards: "Oscar des Meilleurs Effets Visuels",
    },
  },
  {
    id: "3",
    title: "Blade Runner 2049",
    originalTitle: "Blade Runner 2049",
    releaseYear: 2017,
    durationMinutes: 164,
    durationFormatted: "2h 44m",
    director: "Denis Villeneuve",
    genres: ["Science-Fiction", "Mystère", "Thriller"],
    tags: ["Cyberpunk", "Neo-noir", "Replicants", "Esthétique"],
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    synopsis: "En 2049, la société est fragilisée par les tensions entre les humains et les réplicants. L'officier K déterre un secret enfoui depuis des décennies capable d'anéantir ce qui reste de l'ordre mondial.",
    weightedRating: 4.7,
    ratingsCount: 9800,
    hasOscars: true,
    oscarsCount: 2,
    details: {
      boxOffice: "$267M",
      budget: "$150M",
      country: "USA",
      language: "Anglais",
      awards: "2 Oscars (Photographie Roger Deakins, Effets Visuels)",
    },
  },
  {
    id: "4",
    title: "Parasite",
    originalTitle: "Gisaengchung",
    releaseYear: 2019,
    durationMinutes: 132,
    durationFormatted: "2h 12m",
    director: "Bong Joon-ho",
    genres: ["Thriller", "Drame", "Comédie Noire"],
    tags: ["Lutte des classes", "Palme d'Or", "Tension", "Maîtrise"],
    posterUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1478760329108-5c3ed9d495a0?w=1600&auto=format&fit=crop&q=80",
    synopsis: "Toute la famille de Ki-taek est au chômage et s'intéresse de près au train de vie de la richissime famille Park. Une succession de ruses leur permet d'infiltrer méthodiquement la maison.",
    weightedRating: 4.8,
    ratingsCount: 16100,
    hasOscars: true,
    oscarsCount: 4,
    details: {
      boxOffice: "$263M",
      budget: "$15M",
      country: "Corée du Sud",
      language: "Coréen",
      awards: "4 Oscars dont Meilleur Film & Réalisateur, Palme d'Or",
    },
  },
  {
    id: "5",
    title: "Dune: Deuxième Partie",
    originalTitle: "Dune: Part Two",
    releaseYear: 2024,
    durationMinutes: 166,
    durationFormatted: "2h 46m",
    director: "Denis Villeneuve",
    genres: ["Science-Fiction", "Aventure", "Drame"],
    tags: ["Épopée", "Sable", "Prophétie", "Hans Zimmer"],
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80",
    synopsis: "Paul Atréides s'unit à Chani et aux Fremen tout en préparant sa revanche contre les conspirateurs qui ont détruit sa famille. Face à un choix entre l'amour et le destin de l'univers, il devra empêcher un futur funeste.",
    weightedRating: 4.8,
    ratingsCount: 11400,
    hasOscars: false,
    sagaId: "dune-saga",
    details: {
      boxOffice: "$714M",
      budget: "$190M",
      country: "USA",
      language: "Anglais",
      awards: "Nommé pour multiples distinctions",
    },
  },
  {
    id: "6",
    title: "Whiplash",
    originalTitle: "Whiplash",
    releaseYear: 2014,
    durationMinutes: 106,
    durationFormatted: "1h 46m",
    director: "Damien Chazelle",
    genres: ["Drame", "Musique"],
    tags: ["Batterie", "Perfectionnisme", "Jazz", "Intense"],
    posterUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&auto=format&fit=crop&q=80",
    synopsis: "Andrew, 19 ans, rêve de devenir l'un des meilleurs batteurs de jazz de sa génération. Mais la concurrence est féroce au conservatoire de Manhattan, dirigé par l'intransigeant professeur Terence Fletcher.",
    weightedRating: 4.7,
    ratingsCount: 13200,
    hasOscars: true,
    oscarsCount: 3,
    details: {
      boxOffice: "$49M",
      budget: "$3.3M",
      country: "USA",
      language: "Anglais",
      awards: "3 Oscars (Second Rôle J.K. Simmons, Montage, Son)",
    },
  },
  {
    id: "7",
    title: "Oppenheimer",
    originalTitle: "Oppenheimer",
    releaseYear: 2023,
    durationMinutes: 180,
    durationFormatted: "3h 00m",
    director: "Christopher Nolan",
    genres: ["Drame", "Histoire", "Biopic"],
    tags: ["Bombe atomique", "Physique", "Guerre froide", "Trahison"],
    posterUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80",
    synopsis: "Le parcours fascinant du brillant physicien J. Robert Oppenheimer à la tête du Projet Manhattan et les conséquences éthiques et politiques du premier essai nucléaire Trinity.",
    weightedRating: 4.7,
    ratingsCount: 17400,
    hasOscars: true,
    oscarsCount: 7,
    sagaId: "nolan-mind",
    details: {
      boxOffice: "$975M",
      budget: "$100M",
      country: "USA",
      language: "Anglais",
      awards: "7 Oscars dont Meilleur Film, Réalisateur, Acteur (Cillian Murphy)",
    },
  },
  {
    id: "8",
    title: "The Batman",
    originalTitle: "The Batman",
    releaseYear: 2022,
    durationMinutes: 176,
    durationFormatted: "2h 56m",
    director: "Matt Reeves",
    genres: ["Action", "Crime", "Drame"],
    tags: ["Enquête", "Noir", "Gotham", "Detective"],
    posterUrl: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    synopsis: "Deux ans passés à arpenter les rues sous le costume de Batman ont plongé Bruce Wayne au cœur des ténèbres de Gotham. Un tueur s'en prend à l'élite et laisse des indices cryptés.",
    weightedRating: 4.5,
    ratingsCount: 12100,
    hasOscars: false,
    details: {
      boxOffice: "$772M",
      budget: "$185M",
      country: "USA",
      language: "Anglais",
      awards: "Nommé pour 3 Oscars",
    },
  },
];

export const MOCK_SAGA_EPISODES: Record<string, SagaEpisode[]> = {
  "nolan-mind": [
    {
      id: "1",
      title: "Inception",
      releaseYear: 2010,
      orderInSaga: 1,
      posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
      weightedRating: 4.8,
      durationFormatted: "2h 28m",
    },
    {
      id: "2",
      title: "Interstellar",
      releaseYear: 2014,
      orderInSaga: 2,
      posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
      weightedRating: 4.9,
      durationFormatted: "2h 49m",
    },
    {
      id: "7",
      title: "Oppenheimer",
      releaseYear: 2023,
      orderInSaga: 3,
      posterUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&auto=format&fit=crop&q=80",
      weightedRating: 4.7,
      durationFormatted: "3h 00m",
    },
  ],
  "dune-saga": [
    {
      id: "5-part1",
      title: "Dune: Première Partie",
      releaseYear: 2021,
      orderInSaga: 1,
      posterUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80",
      weightedRating: 4.5,
      durationFormatted: "2h 35m",
    },
    {
      id: "5",
      title: "Dune: Deuxième Partie",
      releaseYear: 2024,
      orderInSaga: 2,
      posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
      weightedRating: 4.8,
      durationFormatted: "2h 46m",
    },
  ],
};

export const MOCK_PROFILE: Profil = {
  id: "u1",
  pseudo: "Alice",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
  bio: "Amoureuse de pellicule 70mm, obsédée par la mise en scène de Denis Villeneuve et les plans séquences.",
  favoriteFilm: {
    id: "2",
    title: "Interstellar",
    posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    releaseYear: 2014,
  },
  favoriteGenre: "Science-Fiction",
  stats: {
    totalFilmsWatched: 428,
    totalHoursWatched: 942,
    averageRatingGiven: 4.1,
    totalReviews: 87,
  },
};

export const MOCK_JOURNAL: JournalEntry[] = [
  {
    id: "j1",
    filmId: "2",
    filmTitle: "Interstellar",
    posterUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
    watchedAt: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    note: 5,
    comment: "Revu en IMAX, toujours autant de larmes sur la scène du message vidéo.",
    rewatch: true,
  },
  {
    id: "j2",
    filmId: "7",
    filmTitle: "Oppenheimer",
    posterUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&auto=format&fit=crop&q=80",
    watchedAt: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    note: 4.5,
    comment: "Montage époustouflant, tension permanente jusqu'au procès.",
    rewatch: false,
  },
  {
    id: "j3",
    filmId: "5",
    filmTitle: "Dune: Deuxième Partie",
    posterUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    watchedAt: new Date(Date.now() - 15 * 24 * 3600 * 1000).toISOString(),
    note: 5,
    comment: "La séquence de chevauchée du ver est déjà inscrite dans l'histoire du cinéma.",
    rewatch: false,
  },
];

export const MOCK_LISTS: ListeDetail[] = [
  {
    id: "list-1",
    title: "Voyages dans le Temps & Réalités Parallèles",
    description: "Les plus grands chefs-d'œuvre qui jouent avec les paradoxes temporels et l'illusion de la mémoire.",
    authorPseudo: "Alice",
    authorAvatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80",
    filmCount: 3,
    isPublic: true,
    coverPosters: [
      "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80",
    ],
    createdAt: "2024-01-10T12:00:00Z",
    updatedAt: "2024-03-15T18:30:00Z",
    items: [
      {
        position: 1,
        film: MOCK_FILMS[0],
        addedAt: "2024-01-10T12:05:00Z",
        comment: "La référence absolue sur les strates du rêve.",
      },
      {
        position: 2,
        film: MOCK_FILMS[1],
        addedAt: "2024-01-10T12:10:00Z",
        comment: "La relativité générale transformée en tragédie intime.",
      },
      {
        position: 3,
        film: MOCK_FILMS[2],
        addedAt: "2024-01-12T14:00:00Z",
        comment: "Poésie visuelle inoubliable.",
      },
    ],
  },
  {
    id: "list-2",
    title: "Palmes d'Or & Oscars Incontournables",
    description: "Les films couronnés par la critique et le public qui ont marqué leur décennie.",
    authorPseudo: "MarcCiné",
    authorAvatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    filmCount: 2,
    isPublic: true,
    coverPosters: [
      "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&auto=format&fit=crop&q=80",
    ],
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-02-28T09:15:00Z",
    items: [
      {
        position: 1,
        film: MOCK_FILMS[3],
        addedAt: "2024-02-01T10:05:00Z",
      },
      {
        position: 2,
        film: MOCK_FILMS[6],
        addedAt: "2024-02-02T11:20:00Z",
      },
    ],
  },
];

export const MOCK_POLARIZING_FILMS: PolarizingFilm[] = [
  {
    film: MOCK_FILMS[2], // Blade Runner 2049
    divergenceScore: 88,
    standardDeviation: 1.42,
    positivePercentage: 68,
    negativePercentage: 32,
  },
  {
    film: MOCK_FILMS[7], // The Batman
    divergenceScore: 76,
    standardDeviation: 1.28,
    positivePercentage: 62,
    negativePercentage: 38,
  },
];

export const MOCK_RANKING_DIRECTORS: RankingDirector[] = [
  {
    directorId: "d1",
    name: "Christopher Nolan",
    photoUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80",
    averageRating: 4.8,
    filmCount: 12,
    topFilms: [
      { id: "2", title: "Interstellar", weightedRating: 4.9, releaseYear: 2014 },
      { id: "1", title: "Inception", weightedRating: 4.8, releaseYear: 2010 },
      { id: "7", title: "Oppenheimer", weightedRating: 4.7, releaseYear: 2023 },
    ],
  },
  {
    directorId: "d2",
    name: "Denis Villeneuve",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop&q=80",
    averageRating: 4.75,
    filmCount: 10,
    topFilms: [
      { id: "5", title: "Dune: Deuxième Partie", weightedRating: 4.8, releaseYear: 2024 },
      { id: "3", title: "Blade Runner 2049", weightedRating: 4.7, releaseYear: 2017 },
    ],
  },
  {
    directorId: "d3",
    name: "Bong Joon-ho",
    photoUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop&q=80",
    averageRating: 4.7,
    filmCount: 8,
    topFilms: [
      { id: "4", title: "Parasite", weightedRating: 4.8, releaseYear: 2019 },
    ],
  },
];

export const MOCK_RANKING_GENRES: RankingGenre[] = [
  {
    genre: "Science-Fiction",
    totalFilmsInGenre: 142,
    topFilms: [MOCK_FILMS[1], MOCK_FILMS[0], MOCK_FILMS[4], MOCK_FILMS[2]],
  },
  {
    genre: "Thriller",
    totalFilmsInGenre: 98,
    topFilms: [MOCK_FILMS[3], MOCK_FILMS[0], MOCK_FILMS[7]],
  },
  {
    genre: "Drame",
    totalFilmsInGenre: 215,
    topFilms: [MOCK_FILMS[3], MOCK_FILMS[6], MOCK_FILMS[5]],
  },
];

export const MOCK_SUGGESTIONS: Suggestion[] = [
  {
    film: MOCK_FILMS[0],
    matchScore: 98,
    reason: "Recommandé car vous avez adoré Interstellar et la science-fiction cérébrale.",
  },
  {
    film: MOCK_FILMS[2],
    matchScore: 94,
    reason: "Idéal pour votre passion des ambiances visuelles contemplatives et néo-noir.",
  },
  {
    film: MOCK_FILMS[3],
    matchScore: 91,
    reason: "Plébiscité par 96% des membres qui partagent vos goûts de mise en scène.",
  },
  {
    film: MOCK_FILMS[4],
    matchScore: 89,
    reason: "Suite épique dans le même univers que Dune 1.",
  },
  {
    film: MOCK_FILMS[5],
    matchScore: 87,
    reason: "Une montée d'intensité dramatique saluée par tous les mélomanes.",
  },
];
